[package]
name = "sancov-dumper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib", "staticlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
lazy_static = "1.4"
libc = "0.2"

[build-dependencies]
bindgen = "0.59"
